name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main  # Set this to the branch you want to trigger deployments

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: npm install # Set up dependencies if needed

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.FIREBASE_TOKEN}}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIRL_SCOUT_COOKIES_APP}}'
        projectId: "girl-scout-cookies-app"
